version: "3.8"

services:
  postgres:
    image: postgres:16
    container_name: postgres-db
    restart: always
    environment: 
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - rockpaperscissors_network



  mongo:
    image: mongo:latest
    container_name: mongo-db
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - rockpaperscissors_network


  webapi:
    build:
      context: ./Backend
      dockerfile: RockPaperScissors.WebAPI/Dockerfile
    container_name: webapi
    restart: always
    depends_on:
      - postgres
      - mongo
    environment:
      ConnectionStrings__Postgres: "Host=posgres;Port=5432;Database=rpsgame;Username=postgres;Password=password"
      MongoSetting__ConnectionString: "mongodb://mongo:27017"
      MongoSettings__DatabaseName: "RockPaperScissorsDB"
    ports:
      - "8080:8080"
    networks:
      - rockpaperscissors_network
    volumes:
      - data_protection:/root/.aspnet/DataProtection-Keys
    
  frontend:
    build:
      context: ./Frontend
      dockerfile: Dockerfile
    container_name: frontend
    restart: always
    ports:
      - "5173:80"
    networks:
      - rockpaperscissors_network
    depends_on:
      - webapi
      

    

volumes:
  postgres-data:
  mongo-data:
  data_protection:

networks:
  rockpaperscissors_network:
    driver: bridge